const express = require('express');
const multer = require('multer');
const archiver = require('archiver');
const AdmZip = require('adm-zip');
const fs = require('fs');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3000;

/* ===================================================================
   路径配置
   =================================================================== */

const SITE_DIR = path.join(__dirname, 'site');
const ADMIN_DIR = path.join(__dirname, 'admin');
const DATA_DIR = path.join(__dirname, 'data');
const UPLOADS_DIR = path.join(__dirname, 'uploads');
const THEMES_DIR = path.join(__dirname, 'themes');
const DIST_DIR = path.join(__dirname, 'dist');
const CONFIG_PATH = path.join(DATA_DIR, 'config.json');

// 确保目录存在
[DATA_DIR, UPLOADS_DIR, THEMES_DIR, DIST_DIR].forEach(dir => {
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
});

/* ===================================================================
   中间件配置
   =================================================================== */

app.use(express.json({ limit: '10mb' }));
app.use('/admin/css', express.static(path.join(ADMIN_DIR, 'css')));
app.use('/admin/js', express.static(path.join(ADMIN_DIR, 'js')));
app.use('/uploads', express.static(UPLOADS_DIR, { maxAge: '1d' }));

// 图片上传配置
const imageStorage = multer.diskStorage({
    destination: UPLOADS_DIR,
    filename: (req, file, cb) => {
        const ext = path.extname(file.originalname);
        const name = Date.now() + '-' + Math.random().toString(36).slice(2, 8) + ext;
        cb(null, name);
    }
});
const imageUpload = multer({
    storage: imageStorage,
    fileFilter: (req, file, cb) => {
        const allowed = ['image/jpeg', 'image/png', 'image/webp', 'image/gif'];
        cb(null, allowed.includes(file.mimetype));
    }
});

// 主题 ZIP 上传配置
const zipUpload = multer({
    storage: multer.memoryStorage(),
    limits: { fileSize: 50 * 1024 * 1024 },
    fileFilter: (req, file, cb) => cb(null, file.originalname.endsWith('.zip'))
});

/* ===================================================================
   工具函数
   =================================================================== */

function migrateConfig(config) {
    // 确保旧版配置兼容：自动生成 modules 数组
    if (!config.modules || !Array.isArray(config.modules) || config.modules.length === 0) {
        const mods = [];
        if (config.photographer || config.hero) mods.push({ type: 'hero', visible: true });
        if (config.works) mods.push({ type: 'works', visible: true });
        if (config.about) mods.push({ type: 'about', visible: config.about.visible !== false });
        if (config.footer) mods.push({ type: 'footer', visible: true });
        config.modules = mods;
    }
    // 确保旧版 aboutImage 路径兼容
    if (config.aboutImage && typeof config.aboutImage === 'object') {
        config.aboutImage = config.aboutImage.url || '';
    }
    // 确保主题配置存在
    if (!config.theme) config.theme = { active: null };
    if (config.theme && typeof config.theme === 'string') {
        config.theme = { active: config.theme };
    }
    return config;
}

function readConfig() {
    const config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf-8'));
    return migrateConfig(config);
}

function writeConfig(config) {
    fs.writeFileSync(CONFIG_PATH, JSON.stringify(config, null, 4), 'utf-8');
}

function generateConfigJs(config) {
    return `/**\n * Auto-generated by CMS\n * ${new Date().toISOString()}\n */\nconst SITE_CONFIG = ${JSON.stringify(config, null, 4)};\n`;
}

function copyDirSync(src, dest) {
    if (!fs.existsSync(dest)) fs.mkdirSync(dest, { recursive: true });
    for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
        const srcPath = path.join(src, entry.name);
        const destPath = path.join(dest, entry.name);
        entry.isDirectory() ? copyDirSync(srcPath, destPath) : fs.copyFileSync(srcPath, destPath);
    }
}

/* ===================================================================
   API 路由 — 配置
   =================================================================== */

app.get('/api/config', (req, res) => {
    try {
        res.json(readConfig());
    } catch (err) {
        res.status(500).json({ error: 'Failed to read config' });
    }
});

app.put('/api/config', (req, res) => {
    try {
        const config = req.body;
        const required = ['photographer', 'hero', 'works', 'about', 'social', 'footer'];
        for (const key of required) {
            if (!config[key]) return res.status(400).json({ error: `Missing required field: ${key}` });
        }
        migrateConfig(config);
        writeConfig(config);
        res.json({ success: true });
    } catch (err) {
        res.status(500).json({ error: 'Failed to save config' });
    }
});

// JSON 配置上传
const jsonUpload = multer({
    storage: multer.memoryStorage(),
    limits: { fileSize: 10 * 1024 * 1024 },
    fileFilter: (req, file, cb) => cb(null, file.originalname.endsWith('.json'))
});

// 导入旧版配置（JSON 文件上传 + 自动迁移）
app.post('/api/config/import', jsonUpload.single('config'), (req, res) => {
    try {
        if (!req.file) return res.status(400).json({ error: 'No file uploaded' });
        const raw = req.file.buffer.toString('utf-8');
        let imported;
        try {
            imported = JSON.parse(raw);
        } catch (e) {
            return res.status(400).json({ error: '无效的 JSON 格式' });
        }
        // 宽松验证：至少包含 photographer 和 footer
        if (!imported.photographer || !imported.footer) {
            return res.status(400).json({ error: 'JSON 缺少必要字段（photographer / footer）' });
        }
        // 自动迁移旧版配置
        migrateConfig(imported);
        // 回写缺少但必要的字段
        if (!imported.hero) imported.hero = { image: '', scrollHint: '' };
        if (!imported.works) imported.works = { heading: '', items: [] };
        if (!imported.about) imported.about = { visible: false, role: '', bio: [], stats: [] };
        if (!imported.social) imported.social = { links: [] };
        if (!imported.theme) imported.theme = { active: null };
        if (!imported.aboutImage) imported.aboutImage = '';
        // 保存
        writeConfig(imported);
        res.json({ success: true, message: '配置导入成功，旧版字段已自动迁移' });
    } catch (err) {
        res.status(500).json({ error: '导入失败: ' + err.message });
    }
});

app.post('/api/upload', imageUpload.single('image'), (req, res) => {
    if (!req.file) return res.status(400).json({ error: 'No file uploaded or invalid type' });
    res.json({ url: '/uploads/' + req.file.filename });
});

app.get('/api/images', (req, res) => {
    try {
        const files = fs.readdirSync(UPLOADS_DIR).filter(f => /\.(jpg|jpeg|png|gif|webp)$/i.test(f));
        res.json(files.map(f => ({
            filename: f,
            url: '/uploads/' + f,
            size: fs.statSync(path.join(UPLOADS_DIR, f)).size
        })));
    } catch (err) {
        res.status(500).json({ error: 'Failed to list images' });
    }
});

app.delete('/api/images/:filename', (req, res) => {
    const filePath = path.join(UPLOADS_DIR, req.params.filename);
    if (!fs.existsSync(filePath)) return res.status(404).json({ error: 'File not found' });
    fs.unlinkSync(filePath);
    res.json({ success: true });
});

/* ===================================================================
   API 路由 — 主题
   =================================================================== */

app.get('/api/themes', (req, res) => {
    try {
        const config = readConfig();
        const activeTheme = (config.theme && config.theme.active) || null;
        const themes = [];

        if (fs.existsSync(THEMES_DIR)) {
            fs.readdirSync(THEMES_DIR).forEach(name => {
                const themePath = path.join(THEMES_DIR, name);
                if (fs.statSync(themePath).isDirectory()) {
                    const metaPath = path.join(themePath, 'theme.json');
                    let metadata = null;
                    if (fs.existsSync(metaPath)) {
                        try {
                            metadata = JSON.parse(fs.readFileSync(metaPath, 'utf-8'));
                        } catch (e) { /* ignore invalid theme.json */ }
                    }
                    themes.push({
                        name,
                        label: (metadata && metadata.label) || name,
                        description: (metadata && metadata.description) || '',
                        author: (metadata && metadata.author) || '',
                        version: (metadata && metadata.version) || '',
                        hasHtml: fs.existsSync(path.join(themePath, 'index.html')),
                        hasCss: fs.existsSync(path.join(themePath, 'css'))
                    });
                }
            });
        }
        res.json({ themes, active: activeTheme });
    } catch (err) {
        res.status(500).json({ error: 'Failed to list themes' });
    }
});

app.post('/api/themes/upload', zipUpload.single('theme'), (req, res) => {
    try {
        if (!req.file) return res.status(400).json({ error: 'No file uploaded' });
        const zip = new AdmZip(req.file.buffer);
        const themeName = req.file.originalname.replace(/\.zip$/i, '').replace(/[^a-zA-Z0-9_\-\u4e00-\u9fff]/g, '_');
        const themePath = path.join(THEMES_DIR, themeName);

        zip.extractAllTo(themePath, true);

        const hasHtml = fs.existsSync(path.join(themePath, 'index.html'));
        const hasCss = fs.existsSync(path.join(themePath, 'css'));
        const hasMeta = fs.existsSync(path.join(themePath, 'theme.json'));
        if (!hasHtml && !hasCss) {
            fs.rmSync(themePath, { recursive: true });
            return res.status(400).json({ error: 'ZIP must contain index.html or css/ directory' });
        }
        res.json({ success: true, name: themeName, hasHtml, hasCss, hasMeta });
    } catch (err) {
        res.status(500).json({ error: 'Failed to extract theme: ' + err.message });
    }
});

app.post('/api/themes/:name/activate', (req, res) => {
    try {
        const config = readConfig();
        if (!config.theme) config.theme = {};
        config.theme.active = req.params.name === '__default__' ? null : req.params.name;
        writeConfig(config);
        res.json({ success: true, active: config.theme.active });
    } catch (err) {
        res.status(500).json({ error: 'Failed to activate theme' });
    }
});

app.delete('/api/themes/:name', (req, res) => {
    try {
        const themePath = path.join(THEMES_DIR, req.params.name);
        if (!fs.existsSync(themePath)) return res.status(404).json({ error: 'Theme not found' });
        fs.rmSync(themePath, { recursive: true });

        // 如果删除的是当前激活主题，重置为默认
        const config = readConfig();
        if (config.theme && config.theme.active === req.params.name) {
            config.theme.active = null;
            writeConfig(config);
        }
        res.json({ success: true });
    } catch (err) {
        res.status(500).json({ error: 'Failed to delete theme' });
    }
});

/* ===================================================================
   API 路由 — 导出
   =================================================================== */

app.post('/api/export', (req, res) => {
    try {
        // 清理并重建 dist 目录
        if (fs.existsSync(DIST_DIR)) fs.rmSync(DIST_DIR, { recursive: true });
        fs.mkdirSync(DIST_DIR, { recursive: true });

        // 复制站点文件
        copyDirSync(SITE_DIR, DIST_DIR);

        // 生成 config.js
        const config = readConfig();
        const jsDir = path.join(DIST_DIR, 'js');
        if (!fs.existsSync(jsDir)) fs.mkdirSync(jsDir, { recursive: true });
        fs.writeFileSync(path.join(jsDir, 'config.js'), generateConfigJs(config), 'utf-8');

        // 为 hero 图片添加 preload
        const heroImage = config.hero && config.hero.image;
        if (heroImage) {
            const indexPath = path.join(DIST_DIR, 'index.html');
            if (fs.existsSync(indexPath)) {
                let html = fs.readFileSync(indexPath, 'utf-8');
                const preloadLink = `<link rel="preload" as="image" href="${heroImage}">`;
                html = html.replace('</head>', `    ${preloadLink}\n</head>`);
                fs.writeFileSync(indexPath, html, 'utf-8');
            }
        }

        // 复制激活的主题文件（覆盖默认站点文件）
        if (config.theme && config.theme.active) {
            const themePath = path.join(THEMES_DIR, config.theme.active);
            if (fs.existsSync(themePath)) copyDirSync(themePath, DIST_DIR);
        }

        // 复制上传的图片
        if (fs.existsSync(UPLOADS_DIR) && fs.readdirSync(UPLOADS_DIR).length > 0) {
            copyDirSync(UPLOADS_DIR, path.join(DIST_DIR, 'uploads'));
        }

        res.json({ success: true, path: DIST_DIR });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

app.get('/api/export/download', (req, res) => {
    if (!fs.existsSync(DIST_DIR)) {
        return res.status(404).json({ error: 'Export not found. Run export first.' });
    }
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', 'attachment; filename=photographer-portfolio.zip');
    const archive = archiver('zip', { zlib: { level: 9 } });
    archive.on('error', err => res.status(500).json({ error: err.message }));
    archive.pipe(res);
    archive.directory(DIST_DIR, false);
    archive.finalize();
});

/* ===================================================================
   动态路由 — config.js
   =================================================================== */

app.get('/js/config.js', (req, res) => {
    try {
        res.setHeader('Content-Type', 'application/javascript');
        res.setHeader('Cache-Control', 'no-cache');
        res.send(generateConfigJs(readConfig()));
    } catch (err) {
        res.status(500).send('// Error loading config');
    }
});

/* ===================================================================
   主题中间件 — 优先加载激活主题的文件
   =================================================================== */

app.use((req, res, next) => {
    if (req.path.startsWith('/api') || req.path.startsWith('/admin')) return next();
    try {
        const config = readConfig();
        const themeName = config.theme && config.theme.active;
        if (!themeName) return next();

        const themePath = path.join(THEMES_DIR, themeName);
        const filePath = path.join(themePath, req.path === '/' ? 'index.html' : req.path);
        if (!filePath.startsWith(themePath)) return next();

        if (fs.existsSync(filePath) && fs.statSync(filePath).isFile()) {
            const ext = path.extname(filePath).toLowerCase();
            const mimes = { '.html': 'text/html', '.css': 'text/css', '.js': 'application/javascript',
                            '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.png': 'image/png',
                            '.gif': 'image/gif', '.webp': 'image/webp', '.svg': 'image/svg+xml',
                            '.json': 'application/json', '.woff2': 'font/woff2', '.woff': 'font/woff' };
            res.set('Content-Type', mimes[ext] || 'application/octet-stream');
            res.set('Cache-Control', 'no-cache, no-store, must-revalidate');
            res.set('Pragma', 'no-cache');
            return res.send(fs.readFileSync(filePath));
        }
    } catch (e) { /* 忽略错误，继续默认处理 */ }
    next();
});

/* ===================================================================
   静态文件 & 管理后台
   =================================================================== */

// 管理后台（禁用缓存确保始终最新）
app.get('/admin', (req, res) => {
    res.set('Content-Type', 'text/html');
    res.set('Cache-Control', 'no-cache, no-store, must-revalidate');
    res.send(fs.readFileSync(path.join(ADMIN_DIR, 'index.html')));
});
// 静态站点文件（ETag+max-age=0 确保浏览器每次都向服务器验证）
app.use(express.static(SITE_DIR));
/* ===================================================================
   错误处理 & 启动
   =================================================================== */

app.use((err, req, res, next) => {
    console.error(err);
    res.status(500).json({ error: err.message || 'Internal server error' });
});

app.listen(PORT, () => {
    console.log(`\n  Photographer CMS`);
    console.log(`  ────────────────`);
    console.log(`  Frontend:  http://localhost:${PORT}`);
    console.log(`  Admin:     http://localhost:${PORT}/admin`);
    console.log(`  ────────────────\n`);
});
